apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a2itp4loz-go 
  janus-idp.io/tekton: a2itp4loz-go
  backstage.io/kubernetes-id: a2itp4loz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a2itp4loz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  